import { createContext, useContext, useState } from 'react';

const translations = {
  uz: {
    home: 'Bosh sahifa',
    about: 'Haqida',
    news: 'Yangiliklar',
    search: 'Qidirish...',
    moreInfo: "Ko'proq",
    featured: 'Asosiy Maqola',
    latest: 'So\'nggi Maqolalar',
    recommended: 'Tavsiya Etilgan',
    back: '← Orqaga',
    noArticles: 'Maqolalar topilmadi',
    readMore: "Batafsil o'qish",
    author: 'Muallif',
    keywords: 'Kalit so\'zlar',
    abstract: 'Annotatsiya',
    introduction: 'Kirish',
    literatureReview: 'Adabiyotlar tahlili',
    methodology: 'Metodologiya',
    analysisResults: 'Tahlil natijalari',
    conclusion: 'Xulosa',
    references: 'Adabiyotlar ro\'yxati',
    adminLogin: 'Admin kirish',
    username: 'Foydalanuvchi nomi',
    password: 'Parol',
    login: 'Kirish',
    loginError: 'Noto\'g\'ri ma\'lumotlar',
    dashboard: 'Boshqaruv paneli',
    articles: 'Maqolalar',
    settings: 'Sozlamalar',
    addArticle: 'Maqola qo\'shish',
    editArticle: 'Maqolani tahrirlash',
    deleteArticle: 'Maqolani o\'chirish',
    deleteConfirm: 'Haqiqatan ham o\'chirmoqchimisiz?',
    save: 'Saqlash',
    cancel: 'Bekor qilish',
    logout: 'Chiqish',
    brandName: 'Sayт nomi',
    telegramLink: 'Telegram havolasi',
    instagramLink: 'Instagram havolasi',
    logo: 'Logotip',
    upload: 'Yuklash',
    photo: 'Rasm',
    hashtags: 'Teglar (vergul bilan ajrating)',
    noImage: 'Rasm yo\'q',
    loading: 'Yuklanmoqda...',
    searchResults: 'Qidiruv natijalari',
    allArticles: 'Barcha maqolalar',
    publishedAt: 'E\'lon qilingan',
  },
  ru: {
    home: 'Главная',
    about: 'О нас',
    news: 'Новости',
    search: 'Поиск...',
    moreInfo: 'Подробнее',
    featured: 'Главная Статья',
    latest: 'Последние Статьи',
    recommended: 'Рекомендуемые',
    back: '← Назад',
    noArticles: 'Статьи не найдены',
    readMore: 'Читать далее',
    author: 'Автор',
    keywords: 'Ключевые слова',
    abstract: 'Аннотация',
    introduction: 'Введение',
    literatureReview: 'Обзор литературы',
    methodology: 'Методология',
    analysisResults: 'Результаты анализа',
    conclusion: 'Заключение',
    references: 'Список литературы',
    adminLogin: 'Вход для администратора',
    username: 'Имя пользователя',
    password: 'Пароль',
    login: 'Войти',
    loginError: 'Неверные данные',
    dashboard: 'Панель управления',
    articles: 'Статьи',
    settings: 'Настройки',
    addArticle: 'Добавить статью',
    editArticle: 'Редактировать',
    deleteArticle: 'Удалить',
    deleteConfirm: 'Вы уверены, что хотите удалить?',
    save: 'Сохранить',
    cancel: 'Отмена',
    logout: 'Выйти',
    brandName: 'Название сайта',
    telegramLink: 'Ссылка Telegram',
    instagramLink: 'Ссылка Instagram',
    logo: 'Логотип',
    upload: 'Загрузить',
    photo: 'Фото',
    hashtags: 'Теги (через запятую)',
    noImage: 'Нет изображения',
    loading: 'Загрузка...',
    searchResults: 'Результаты поиска',
    allArticles: 'Все статьи',
    publishedAt: 'Опубликовано',
  },
  en: {
    home: 'Home',
    about: 'About',
    news: 'News',
    search: 'Search...',
    moreInfo: 'More Info',
    featured: 'Featured Article',
    latest: 'Latest Articles',
    recommended: 'Recommended',
    back: '← Back',
    noArticles: 'No articles found',
    readMore: 'Read more',
    author: 'Author',
    keywords: 'Keywords',
    abstract: 'Abstract',
    introduction: 'Introduction',
    literatureReview: 'Literature Review',
    methodology: 'Methodology',
    analysisResults: 'Analysis Results',
    conclusion: 'Conclusion',
    references: 'References',
    adminLogin: 'Admin Login',
    username: 'Username',
    password: 'Password',
    login: 'Login',
    loginError: 'Invalid credentials',
    dashboard: 'Dashboard',
    articles: 'Articles',
    settings: 'Settings',
    addArticle: 'Add Article',
    editArticle: 'Edit Article',
    deleteArticle: 'Delete',
    deleteConfirm: 'Are you sure you want to delete?',
    save: 'Save',
    cancel: 'Cancel',
    logout: 'Logout',
    brandName: 'Brand Name',
    telegramLink: 'Telegram Link',
    instagramLink: 'Instagram Link',
    logo: 'Logo',
    upload: 'Upload',
    photo: 'Photo',
    hashtags: 'Hashtags (comma separated)',
    noImage: 'No Image',
    loading: 'Loading...',
    searchResults: 'Search Results',
    allArticles: 'All Articles',
    publishedAt: 'Published',
  },
};

const LangContext = createContext(null);

export const LangProvider = ({ children }) => {
  const [lang, setLang] = useState('uz');
  const t = (key) => translations[lang][key] || translations.en[key] || key;
  return (
    <LangContext.Provider value={{ lang, setLang, t, translations }}>
      {children}
    </LangContext.Provider>
  );
};

export const useLang = () => useContext(LangContext);
